# 配置Tomcat端口号
server:
  port: 9999
# 配置Spring Boot项目名
spring:
  application:
    name: xmall-server
# 配置Dubbo信息
  dubbo:
    application:
      name: xmall-server
    protocol:
      name: dubbo
      port: 20880
      serialization: java
    registry:
      address: zookeeper://localhost:2181
    scan: com.augustars.xmall
# 配置使用JDK代理方式
  aop:
    proxy-target-class: true
# 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.156:3306/winner?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC
    username: winner
    password: Winner@123456
# 增加JPA配置信息
  jpa:
    show-sql: true
    open-in-view: true